image: node:12.18.2

pipelines:
  branches: # Pipelines that will be triggered when a push is made in the below branch
    main:
      - step:
          name: Create/Update Lambda code
          deployment: Test
          script:
            - pipe: atlassian/aws-sam-deploy:1.2.0
              variables:
                AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
                AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
                AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
                S3_BUCKET: $S3_BUCKET
                STACK_NAME: $STACK_NAME
                CAPABILITIES: ["CAPABILITY_IAM", "CAPABILITY_AUTO_EXPAND"]
